### ISSUE TITLE
Introduce custom page attributes

### ISSUE THREAD

**Issue by boyko-ant** [solidify-project/engine#10]
Custom attributes should be placed in .md file using the following format:

```yaml
custom.image:          ...
custom.description:    ...
costom.something:      ...
```

They should be accessible on a template using `Page.Custom.<name>` format. For example `Page.Custom.image` or `Page.Custom.description`. Attributes names can be case sensitive.
